
gendoc:logo.png
	../../doc/gendoc

logo.png:logo.ps
#	convert -resize 128x128 $< $@
#	convert -resize 384x384 $< -crop 256x128+64+0 $@
#	convert -resize 448x448 $< -crop 128x128+300+40 $@
	convert -resize 448x448 $< -crop 128x128+300+40 $@


